import { createFileRoute } from "@tanstack/react-router";
import { MonitorSmartphone, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { SecurityShell, SecuritySection, CalmNotice } from "@/components/security-ui";

export const Route = createFileRoute("/profile/security/sessions")({ component: SessionsPage });
function SessionsPage() { const [open, setOpen] = useState(false); return <SecurityShell title="Active sessions" description="Review where your MealMate account is signed in. Real session data will appear here when connected."><SecuritySection title="Your devices"><div className="p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-muted p-3 text-primary"><MonitorSmartphone className="h-5 w-5" /></div><div><p className="font-medium">Current device</p><p className="text-sm text-muted-foreground">This session · Active now</p></div><span className="ml-auto rounded-full bg-[#7D9B76]/15 px-2.5 py-1 text-xs font-semibold text-[#52734d]">Current</span></div></div></SecuritySection><CalmNotice>No other active sessions are available to display right now.</CalmNotice><Button variant="outline" className="mt-5 h-12 w-full rounded-xl" onClick={() => setOpen(true)}>Sign out of all devices</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Sign out of all devices?</DialogTitle><DialogDescription>This will end every other MealMate session. You will remain signed in on this device.</DialogDescription></DialogHeader><div className="flex items-center gap-3 rounded-xl bg-muted p-3 text-sm"><ShieldAlert className="h-5 w-5 text-primary" />This action will connect to your existing account security service.</div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => setOpen(false)}>Confirm sign out</Button></DialogFooter></DialogContent></Dialog></SecurityShell>; }
